export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";

export const GET_SERVICES = "GET_SERVICES";

export const GET_SALON = "GET_SALON";
export const GET_SALON_SERVICES = "GET_SALON_SERVICES";

export const LOGIN = "LOGIN";

export const GET_CITIES = "GET_CITIES";

export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const USER = "USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const REGISTER_USER = "REGISTER_USER";
export const ADD_FAVORITE_SERVICE = "ADD_FAVORITE_SERVICE";
export const GET_FAVORITES = "GET_FAVORITES";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FIELD = "UPDATE_USER_FIELD";
export const ADD_TO_BOOKINGS = "ADD_TO_BOOKINGS";
export const REMOVE_FROM_BOOKINGS = "REMOVE_FROM_BOOKINGS";
export const GET_BOOKINGS = "GET_BOOKINGS";
