export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CATEGORY = "SET_CATEGORY";
export const GET_SERVICES = "GET_SERVICES";
export const GET_CITIES = "GET_CITIES";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
